version: '3'

services:
  
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/tmp/mysql
    environment:
       MYSQL_HOST: db
       MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
    expose:
      - "3306"
    
  redis:
    image: redis
    restart: always
    environment:
      REDIS_HOST: redis
    expose:
      - "6379"
  
  elasticsearch:
    image: elasticsearch:7.17.3
    restart: always
    environment:
      - "ELASTICSEARCH_HOST=lasticsearch"
      - "discovery.type=single-node"
    expose:
      - "9200"

  chat-api:
    build: ./ChatAPI-Rails
    restart: always
    depends_on:
      - "db"
      - "redis"
      - "elasticsearch"
    volumes:
      - ".:/chat-api"
    ports:
      - "3000:3000"

  chat-api-go:
    build: ./ChatAPI-Go
    restart: always
    depends_on:
      - "redis"
    volumes:
      - ".:/chat-api-go"
    ports:
      - "8080:8080"
  