
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'


default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  host: db
  

development:
  <<: *default
  database: ChatAPI_development

test:
  <<: *default
  database: ChatAPI_test

production:
  <<: *default
  database: ChatAPI_production

